import sqlite3
import numpy as np
from datetime import datetime
from db import get_connection
from item import Item

EMBEDDING_DIM = 512
MODEL_NAME = "clip-ViT-B-32"
MATCH_THRESHOLD = 0.75   # derived from the Day 10 similarity experiment


def create_embeddings_table():
    try:
        with get_connection() as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS embeddings (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    item_id INTEGER NOT NULL,
                    vector BLOB NOT NULL,
                    model TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    FOREIGN KEY (item_id) REFERENCES items(id)
                )
            """)
    except Exception as e:
        print(f"  Error creating embeddings table: {e}")


def get_item_id(name):
    try:
        with get_connection() as conn:
            row = conn.execute(
                "SELECT id FROM items WHERE LOWER(name) = LOWER(?)", (name,)
            ).fetchone()
        return row[0] if row else None
    except Exception as e:
        print(f"  Error looking up item id for '{name}': {e}")
        return None


def save_embedding(item_id, vector):
    """vector: normalized numpy float32 array of length EMBEDDING_DIM"""
    try:
        blob = vector.astype(np.float32).tobytes()
        with get_connection() as conn:
            conn.execute("""
                INSERT INTO embeddings (item_id, vector, model, created_at)
                VALUES (?, ?, ?, ?)
            """, (item_id, blob, MODEL_NAME,
                  datetime.now().strftime('%Y-%m-%d %H:%M')))
    except Exception as e:
        print(f"  Error saving embedding: {e}")


def enroll_item(name, category, vectors):
    """Create the item (if new) and store all of its view embeddings.
    Returns the item_id, or None on failure."""
    from db import add_item
    try:
        item_id = get_item_id(name)
        if item_id is None:
            add_item(Item(name, 1, category))   # enrollment implies 1 in storage
            item_id = get_item_id(name)
        if item_id is None:
            print(f"  Could not create or find item '{name}'.")
            return None
        for v in vectors:
            save_embedding(item_id, v)
        print(f"  Enrolled '{name}' with {len(vectors)} views.")
        return item_id
    except Exception as e:
        print(f"  Error enrolling '{name}': {e}")
        return None


def load_catalog():
    """Returns list of (item_name, vector) for every stored view
    generated by the current embedding model."""
    try:
        with get_connection() as conn:
            rows = conn.execute("""
                SELECT items.name, embeddings.vector
                FROM embeddings
                JOIN items ON embeddings.item_id = items.id
                WHERE embeddings.model = ?
            """, (MODEL_NAME,)).fetchall()
        return [(name, np.frombuffer(blob, dtype=np.float32))
                for name, blob in rows]
    except Exception as e:
        print(f"  Error loading catalog: {e}")
        return []


def match_item(query_vector, threshold=MATCH_THRESHOLD):
    """Compare a query embedding against every stored view.
    Returns (item_name, score) on a match, (None, best_score) on unknown."""
    catalog = load_catalog()
    if not catalog:
        return None, 0.0

    best_name, best_score = None, -1.0
    for name, vector in catalog:
        score = float(np.dot(query_vector, vector))   # both normalized → dot = cosine
        if score > best_score:
            best_name, best_score = name, score

    if best_score >= threshold:
        return best_name, best_score
    return None, best_score
def reset_catalog():
    with get_connection() as conn:
        conn.execute("DELETE FROM embeddings")
    print("  Catalog cleared.")

def get_view_count(name):
    """How many views are stored for an item — useful for the UI later."""
    item_id = get_item_id(name)
    if item_id is None:
        return 0
    try:
        with get_connection() as conn:
            row = conn.execute("""
                SELECT COUNT(*) FROM embeddings
                WHERE item_id = ? AND model = ?
            """, (item_id, MODEL_NAME)).fetchone()
        return row[0]
    except Exception as e:
        print(f"  Error counting views: {e}")
        return 0
    
